//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rsi.jg.org/", ConfigurationName="ServiceReference1.HelloWorldImpl")]
    public interface HelloWorldImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsi.jg.org/HelloWorldImpl/getHelloWorldAsStringRequest", ReplyAction="http://rsi.jg.org/HelloWorldImpl/getHelloWorldAsStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getHelloWorldAsStringResponse> getHelloWorldAsStringAsync(ServiceReference1.getHelloWorldAsStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsi.jg.org/HelloWorldImpl/getMoviesRequest", ReplyAction="http://rsi.jg.org/HelloWorldImpl/getMoviesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getMoviesResponse> getMoviesAsync(ServiceReference1.getMoviesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHelloWorldAsString", WrapperNamespace="http://rsi.jg.org/", IsWrapped=true)]
    public partial class getHelloWorldAsStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsi.jg.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getHelloWorldAsStringRequest()
        {
        }
        
        public getHelloWorldAsStringRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHelloWorldAsStringResponse", WrapperNamespace="http://rsi.jg.org/", IsWrapped=true)]
    public partial class getHelloWorldAsStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsi.jg.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getHelloWorldAsStringResponse()
        {
        }
        
        public getHelloWorldAsStringResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsi.jg.org/")]
    public partial class Film
    {
        
        private string dataField;
        
        private string[] miejscaField;
        
        private string godzinaField;
        
        private string tytulField;
        
        private byte[] zdjecieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("miejsca", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] miejsca
        {
            get
            {
                return this.miejscaField;
            }
            set
            {
                this.miejscaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string godzina
        {
            get
            {
                return this.godzinaField;
            }
            set
            {
                this.godzinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tytul
        {
            get
            {
                return this.tytulField;
            }
            set
            {
                this.tytulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] zdjecie
        {
            get
            {
                return this.zdjecieField;
            }
            set
            {
                this.zdjecieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMovies", WrapperNamespace="http://rsi.jg.org/", IsWrapped=true)]
    public partial class getMoviesRequest
    {
        
        public getMoviesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMoviesResponse", WrapperNamespace="http://rsi.jg.org/", IsWrapped=true)]
    public partial class getMoviesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsi.jg.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.Film[] @return;
        
        public getMoviesResponse()
        {
        }
        
        public getMoviesResponse(ServiceReference1.Film[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface HelloWorldImplChannel : ServiceReference1.HelloWorldImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HelloWorldImplClient : System.ServiceModel.ClientBase<ServiceReference1.HelloWorldImpl>, ServiceReference1.HelloWorldImpl
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HelloWorldImplClient() : 
                base(HelloWorldImplClient.GetDefaultBinding(), HelloWorldImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HelloWorldImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HelloWorldImplClient(EndpointConfiguration endpointConfiguration) : 
                base(HelloWorldImplClient.GetBindingForEndpoint(endpointConfiguration), HelloWorldImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HelloWorldImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HelloWorldImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HelloWorldImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HelloWorldImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HelloWorldImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getHelloWorldAsStringResponse> ServiceReference1.HelloWorldImpl.getHelloWorldAsStringAsync(ServiceReference1.getHelloWorldAsStringRequest request)
        {
            return base.Channel.getHelloWorldAsStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getHelloWorldAsStringResponse> getHelloWorldAsStringAsync(string arg0)
        {
            ServiceReference1.getHelloWorldAsStringRequest inValue = new ServiceReference1.getHelloWorldAsStringRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.HelloWorldImpl)(this)).getHelloWorldAsStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getMoviesResponse> ServiceReference1.HelloWorldImpl.getMoviesAsync(ServiceReference1.getMoviesRequest request)
        {
            return base.Channel.getMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getMoviesResponse> getMoviesAsync()
        {
            ServiceReference1.getMoviesRequest inValue = new ServiceReference1.getMoviesRequest();
            return ((ServiceReference1.HelloWorldImpl)(this)).getMoviesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HelloWorldImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HelloWorldImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://desktop-elq50qg:8181/Rezerwacjabilet/HelloWorldImplService");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HelloWorldImplClient.GetBindingForEndpoint(EndpointConfiguration.HelloWorldImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HelloWorldImplClient.GetEndpointAddress(EndpointConfiguration.HelloWorldImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            HelloWorldImplPort,
        }
    }
}
